name: CI

on:
    push:
        branches: [master]
        paths-ignore: ['**.md']
    pull_request:
        branches: [master]
        paths-ignore: ['**.md']

permissions:
    contents: read
    pull-requests: read

concurrency:
    group: ci-${{ github.ref }}
    cancel-in-progress: true

jobs:
    checks:
        name: Format, Lint, Typecheck
        runs-on: ubuntu-latest
        timeout-minutes: 5
        env:
            CI: true
        steps:
            - name: Checkout repository
              uses: actions/checkout@v5

            - name: Setup Node.js 24
              uses: actions/setup-node@v5
              with:
                  node-version: 24
                  cache: npm
                  cache-dependency-path: package-lock.json

            - name: Install dependencies
              run: npm ci --no-audit --no-fund

            - name: Run format, lint and typecheck
              run: npm run check
