name: CI

on:
    push:
        branches: [master]
        paths-ignore: ['**.md']
    pull_request:
        branches: [master]
        paths-ignore: ['**.md']

permissions:
    contents: read
    pull-requests: read

concurrency:
    group: ci-${{ github.ref }}
    cancel-in-progress: true

jobs:
    checks:
        name: Format, Lint, Typecheck
        runs-on: ubuntu-latest
        timeout-minutes: 5
        env:
            CI: true
        steps:
            - name: Checkout repository
              uses: actions/checkout@v5

            - name: Setup Bun
              uses: oven-sh/setup-bun@v2
              with:
                  bun-version: 1.3.0

            - name: Install dependencies
              run: bun install

            - name: Run format, lint and typecheck
              run: bun run check
