name: CI

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

permissions:
    contents: read
    pull-requests: read

jobs:
    quality:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Use Node.js 24 (stable)
              uses: actions/setup-node@v4
              with:
                  node-version: 24
                  cache: npm

            - name: Install dependencies
              run: npm ci

            - name: Format Check
              run: npm run format:check

            - name: Lint Check
              run: npm run lint:check

            - name: Type Check
              run: npm run typescript:check
